version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://username:password@postgres:port/database
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
